version: '3.8'

services:
  postgres:
    image: timescale/timescaledb-postgis:latest-pg13
    container_name: bnovauto_db
    environment:
      POSTGRES_USER: bnovauto
      POSTGRES_PASSWORD: bnovauto_1234567890
      POSTGRES_DB: bnovauto_db
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bnovauto -d bnovauto_db"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: bnovauto_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bnovauto.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  pgadmin_data: